# POST http://localhost:3000/upload-sessions

# POST http://localhost:3000/upload-sessions/734ce4d0-2641-429f-ad86-975170dab9a4/files
# Content-Type: multipart/form-data; boundary=WebAppBoundary

# --WebAppBoundary
# Content-Disposition: form-data; name="relativePath"

# docs/report.pdf
# --WebAppBoundary
# Content-Disposition: form-data; name="file"; filename="report.pdf"
# Content-Type: application/pdf

# < ./report.pdf
# --WebAppBoundary--

GET http://localhost:3000/upload-sessions/734ce4d0-2641-429f-ad86-975170dab9a4